{
  "openapi": "3.0.1",
  "info": {
    "title": "HTTP-Manager",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "用户"
    },
    {
      "name": "接口"
    },
    {
      "name": "接口/1"
    }
  ],
  "paths": {
    "/api/user": {
      "post": {
        "summary": "注册用户",
        "x-apifox-folder": "用户",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "",
        "tags": [
          "用户"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/user",
                "x-apifox-overrides": {
                  "password": null
                }
              },
              "example": {
                "email": "111@qq.com",
                "name": "用户1",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": 200,
                      "msg": "注册成功!",
                      "data": {
                        "email": "111@qq.com",
                        "name": "用户1",
                        "_id": "64dd7ae412844cc36edc60b4"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3140859/apis/api-102255556-run"
      }
    },
    "/api/upload": {
      "post": {
        "summary": "上传文件",
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "上传swagger文件，返回解析的数据",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "example": "file://C:\\Users\\WhiteNight\\OneDrive\\桌面\\HTTP-Manager.openapi.json",
                    "format": "binary"
                  }
                },
                "required": [
                  "file"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": 200,
                      "msg": "解析文件成功!",
                      "data": [
                        {
                          "name": "更改接口",
                          "description": "修改接口说明",
                          "requestMethod": "PATCH",
                          "requestPath": "/api/interface/:interfaceId",
                          "requestHeaders": [
                            {
                              "name": "Authorization",
                              "description": "必选token",
                              "required": true,
                              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQ1ZDc5YjQwNDhiYmFkMTkyZmYwZWQiLCJpYXQiOjE2OTE4MTA3NjYsImV4cCI6MTY5MjY3NDc2Nn0.Z_u8P4Q8Z1VQ37QNPR64bJIsbA5IqjYEj2aRIZr08T4",
                              "type": "string"
                            }
                          ],
                          "requestParams": {
                            "path": [
                              {
                                "name": "interfaceId",
                                "description": "接口Id",
                                "required": true,
                                "example": "64d782b65239aaa91333922f",
                                "type": "string"
                              }
                            ],
                            "query": []
                          },
                          "requestBody": {
                            "contentType": "application/json",
                            "content": [
                              {
                                "name": "",
                                "array": [
                                  {
                                    "projects": [
                                      {
                                        "school": ""
                                      }
                                    ]
                                  }
                                ],
                                "user": {
                                  "age": ""
                                }
                              }
                            ]
                          },
                          "response": {
                            "contentType": "application/json",
                            "content": [
                              {
                                "code": "200",
                                "msg": "",
                                "data": {
                                  "_id": "",
                                  "name": "",
                                  "historys": [
                                    {
                                      "historyname": ""
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3140859/apis/api-102385639-run"
      }
    },
    "/api/interface/{interfaceId}": {
      "patch": {
        "summary": "更改接口",
        "x-apifox-folder": "接口",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "修改接口说明",
        "tags": [
          "接口"
        ],
        "parameters": [
          {
            "name": "interfaceId",
            "in": "path",
            "description": "接口Id",
            "required": true,
            "example": "64d782b65239aaa91333922f",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "必选token",
            "required": true,
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQ1ZDc5YjQwNDhiYmFkMTkyZmYwZWQiLCJpYXQiOjE2OTE4MTA3NjYsImV4cCI6MTY5MjY3NDc2Nn0.Z_u8P4Q8Z1VQ37QNPR64bJIsbA5IqjYEj2aRIZr08T4",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {},
                "x-apifox-orders": [],
                "x-apifox-ignore-properties": []
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-apifox-refs": {
                    "01H80K35G758VR13TH7TS664WT": {
                      "$ref": "#/components/schemas/interface",
                      "x-apifox-overrides": {
                        "historys": null
                      }
                    }
                  },
                  "x-apifox-orders": [
                    "01H80K35G758VR13TH7TS664WT"
                  ],
                  "properties": {
                    "id": {
                      "type": "string",
                      "title": "接口ID"
                    },
                    "name": {
                      "type": "string",
                      "title": "接口名称"
                    },
                    "description": {
                      "type": "string"
                    },
                    "requestMethod": {
                      "type": "string",
                      "title": "请求方法"
                    },
                    "requestPath": {
                      "type": "string",
                      "title": "接口地址"
                    },
                    "requestHeaders": {
                      "type": "string",
                      "title": "header参数",
                      "description": "JSON.stringify(parameter)"
                    },
                    "requestParams": {
                      "type": "string",
                      "title": "query参数",
                      "description": "JSON.stringify(parameter)"
                    },
                    "requestBody": {
                      "type": "string",
                      "title": "body参数",
                      "description": "JSON.stringify(requestBody)"
                    },
                    "response": {
                      "type": "string",
                      "title": "返回数据",
                      "description": "JSON.stringify(response)"
                    },
                    "projectId": {
                      "type": "string",
                      "title": "所属项目ID"
                    }
                  },
                  "required": [
                    "name",
                    "requestMethod",
                    "requestPath"
                  ],
                  "x-apifox-ignore-properties": [
                    "id",
                    "name",
                    "description",
                    "requestMethod",
                    "requestPath",
                    "requestHeaders",
                    "requestParams",
                    "requestBody",
                    "response",
                    "projectId"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": 200,
                      "msg": "更新接口成功!",
                      "data": {
                        "_id": "64d782b65239aaa91333922f",
                        "name": "查询派蒙88",
                        "description": "22222222222222222222米哈游米哈游米哈游米哈游米哈游米哈游米哈游米哈游米哈游米哈游。",
                        "method": "POST",
                        "url": "http://fvvs.ru/zxhrmkovy",
                        "headers": "nisi eiusmod eu veniam consectetur",
                        "params": "occaecat laborum incididunt est et",
                        "body": "Ut deserunt",
                        "response": "dolor exercitation",
                        "projectId": "64d74390ec1c47299894966b"
                      }
                    }
                  },
                  "2": {
                    "summary": "成功示例",
                    "value": {
                      "code": 200,
                      "msg": "更新接口成功!",
                      "data": {
                        "_id": "64dd7ca612844cc36edc60ec",
                        "name": "米哈游33",
                        "description": "米哈游成立于2011年，致力于为用户提供美好的、超出预期的产品与内容。",
                        "requestMethod": "POST",
                        "requestPath": "/afjsvglp.se/eksey",
                        "requestHeaders": "esse sunt officia occaecat",
                        "requestParams": "exercitation sint proident commodo",
                        "requestBody": "ea dolor",
                        "response": "Ut",
                        "projectId": "64dd7bd112844cc36edc60c4"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3140859/apis/api-102438233-run"
      }
    },
    "/mock/add": {
      "post": {
        "summary": "Mock",
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "将接口上传，后端生成一个Mock接口",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {},
                "x-apifox-ignore-properties": [],
                "x-apifox-orders": []
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": 200,
                      "message": "success"
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3140859/apis/api-103271849-run"
      }
    },
    "/111": {
      "get": {
        "summary": "111",
        "x-apifox-folder": "接口/1",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "",
        "tags": [
          "接口/1"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3140859/apis/api-104827051-run"
      }
    }
  },
  "components": {
    "schemas": {
      "interface": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "title": "接口ID"
          },
          "name": {
            "type": "string",
            "title": "接口名称"
          },
          "description": {
            "type": "string"
          },
          "requestMethod": {
            "type": "string",
            "title": "请求方法"
          },
          "requestPath": {
            "type": "string",
            "title": "接口地址"
          },
          "requestHeaders": {
            "type": "string",
            "title": "header参数",
            "description": "JSON.stringify(parameter)"
          },
          "requestParams": {
            "type": "string",
            "title": "query参数",
            "description": "JSON.stringify(parameter)"
          },
          "requestBody": {
            "type": "string",
            "title": "body参数",
            "description": "JSON.stringify(requestBody)"
          },
          "response": {
            "type": "string",
            "title": "返回数据",
            "description": "JSON.stringify(response)"
          },
          "projectId": {
            "type": "string",
            "title": "所属项目ID"
          },
          "historys": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "version": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                },
                "updatedBy": {
                  "type": "object",
                  "x-apifox-refs": {
                    "01H7PCAM6PKP8MZQR1YX1GSYDJ": {
                      "$ref": "#/components/schemas/user",
                      "x-apifox-overrides": {
                        "password": null
                      }
                    }
                  },
                  "x-apifox-orders": [
                    "01H7PCAM6PKP8MZQR1YX1GSYDJ"
                  ],
                  "properties": {
                    "id": {
                      "type": "string",
                      "title": "用户ID"
                    },
                    "email": {
                      "type": "string",
                      "title": "邮箱"
                    },
                    "name": {
                      "type": "string",
                      "title": "用户名"
                    },
                    "bio": {
                      "type": "string",
                      "title": "个人简介"
                    }
                  },
                  "required": [
                    "email",
                    "name"
                  ],
                  "x-apifox-ignore-properties": [
                    "id",
                    "email",
                    "name",
                    "bio"
                  ]
                },
                "data": {
                  "type": "string"
                }
              },
              "x-apifox-orders": [
                "version",
                "updatedAt",
                "updatedBy",
                "data"
              ],
              "required": [
                "version",
                "updatedBy",
                "data"
              ],
              "x-apifox-ignore-properties": []
            },
            "title": "更改历史",
            "description": "该接口的更改历史记录"
          }
        },
        "x-apifox-orders": [
          "id",
          "name",
          "description",
          "requestMethod",
          "requestPath",
          "requestHeaders",
          "requestParams",
          "requestBody",
          "response",
          "projectId",
          "historys"
        ],
        "required": [
          "name",
          "requestPath",
          "requestMethod"
        ],
        "x-apifox-refs": {},
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": ""
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "title": "用户ID"
          },
          "email": {
            "type": "string",
            "title": "邮箱"
          },
          "name": {
            "type": "string",
            "title": "用户名"
          },
          "password": {
            "type": "string",
            "title": "密码"
          },
          "bio": {
            "type": "string",
            "title": "个人简介"
          }
        },
        "x-apifox-orders": [
          "id",
          "email",
          "name",
          "password",
          "bio"
        ],
        "required": [
          "name",
          "password",
          "email"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": ""
      }
    }
  },
  "servers": []
}